import type { Metadata } from "next";
import Link from "next/link";
import { Calculator, Database, Info, MapPin, Scale, Tag } from "lucide-react";
import { Brand } from "@/components/public/brand";
import { SiteFooter } from "@/components/public/site-footer";

export const metadata: Metadata = { title: "Metodologi Karbon | EcoSpend", description: "Cara EcoSpend menghasilkan estimasi CO₂e, menyimpan sumber faktor, dan menjelaskan ketidakpastian." };

const principles = [
  { icon: Database, title: "Sumber tercatat", text: "Faktor produksi menyertakan penerbit, versi atau tahun, wilayah, satuan, dan masa berlaku." },
  { icon: Scale, title: "Tidak menghitung ganda", text: "Aktivitas dan belanja untuk kejadian yang sama tidak dijumlahkan sebagai dua dampak terpisah." },
  { icon: Info, title: "Batasan terlihat", text: "Metode, keyakinan, dan kekurangan data disampaikan bersama hasil, bukan disembunyikan." },
] as const;

export default function MethodologyPage() {
  return <div className="min-h-screen bg-[#f7f9f4] text-slate-900"><header className="border-b border-emerald-950/10 bg-white"><div className="mx-auto flex min-h-16 max-w-7xl items-center justify-between px-5 sm:px-8 lg:px-10"><Brand /><Link href="/" className="text-sm font-semibold text-emerald-800">Kembali ke beranda</Link></div></header><main>
    <section className="overflow-hidden bg-emerald-950 px-5 py-16 text-white sm:px-8 lg:px-10 lg:py-24"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.2fr_0.8fr]"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-lime-300">Transparansi metodologi</p><h1 className="mt-4 max-w-4xl text-balance text-4xl font-bold tracking-[-0.05em] sm:text-6xl">Memahami angka di balik perkiraan karbon.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-emerald-100/70">EcoSpend mengubah data aktivitas atau pengeluaran menjadi estimasi kilogram karbon dioksida ekuivalen (kg CO₂e). Halaman ini menjelaskan cara kerja dan batasnya.</p></div><div className="rounded-2xl border border-white/10 bg-white/5 p-6"><p className="text-xs font-semibold uppercase tracking-wider text-lime-300">Kesimpulan utama</p><p className="mt-3 text-xl font-semibold leading-8">Angka CO₂e adalah petunjuk untuk refleksi pribadi—bukan pengukuran, audit, atau sertifikasi.</p></div></div></section>
    <section className="px-5 py-16 sm:px-8 lg:px-10 lg:py-24"><div className="mx-auto max-w-7xl"><div className="grid gap-5 md:grid-cols-3">{principles.map(({icon: Icon,title,text}) => <article key={title} className="rounded-2xl border border-emerald-950/10 bg-white p-6"><span className="grid size-11 place-items-center rounded-xl bg-emerald-100 text-emerald-800"><Icon className="size-5" aria-hidden="true" /></span><h2 className="mt-5 text-lg font-bold text-emerald-950">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></div></section>
    <MethodSection number="01" title="Dua pendekatan estimasi"><div className="grid gap-5 md:grid-cols-2"><MethodCard icon={MapPin} title="Berbasis aktivitas" formula="jumlah aktivitas × faktor emisi" text="Diprioritaskan ketika data seperti kilometer, kWh, liter, atau massa tersedia dan satuannya cocok dengan faktor." /><MethodCard icon={Tag} title="Berbasis pengeluaran" formula="nilai belanja terselaras × intensitas emisi" text="Digunakan ketika data aktivitas tidak ada. Mata uang, tahun harga, wilayah, dan sektor perlu diselaraskan; ketidakpastiannya umumnya lebih tinggi." /></div></MethodSection>
    <MethodSection number="02" title="Dari transaksi menjadi estimasi"><ol className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[['1','Klasifikasi','Transaksi dipetakan ke aktivitas atau kategori sektor.'],['2','Pencocokan','Faktor dipilih menurut satuan, wilayah, kategori, dan periode.'],['3','Perhitungan','Jumlah dikalikan faktor tanpa pembulatan prematur.'],['4','Snapshot','Nilai faktor, sumber, versi, dan metode disimpan bersama hasil.']].map(([n,t,d]) => <li key={n} className="rounded-2xl bg-emerald-50 p-5"><span className="font-mono text-sm text-emerald-700">{n}</span><h3 className="mt-4 font-bold text-emerald-950">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{d}</p></li>)}</ol></MethodSection>
    <MethodSection number="03" title="Provenance faktor"><p>Faktor yang layak digunakan pada data produksi harus menyimpan nama sumber atau penerbit, URL atau referensi, versi, tanggal publikasi dan akses bila tersedia, wilayah, periode berlaku, cakupan gas, satuan aktivitas, serta catatan metodologi. Snapshot faktor membuat hasil lama tetap dapat ditelusuri ketika faktor diperbarui.</p><p className="mt-4">Faktor demo bersifat sintetis atau disederhanakan. Faktor tersebut harus ditandai dan tidak boleh digunakan untuk klaim resmi.</p></MethodSection>
    <MethodSection number="04" title="Ketidakpastian dan kualitas"><p>Hasil dipengaruhi detail aktivitas, ketepatan kategori, batas sistem sumber, karakteristik lokal, tahun data, inflasi, kurs, dan variasi rantai pasok. Label keyakinan adalah komunikasi kualitas input dan kecocokan faktor, bukan interval statistik kecuali metodologi sumber memang menyediakannya.</p><div className="mt-6 grid gap-3 sm:grid-cols-3"><Confidence label="Tinggi" text="Aktivitas dan satuan spesifik cocok dengan faktor yang relevan." color="bg-emerald-700" /><Confidence label="Sedang" text="Kategori sesuai tetapi detail aktivitas atau lokalitas terbatas." color="bg-amber-500" /><Confidence label="Rendah" text="Mengandalkan kategori luas, nilai belanja, atau faktor proksi." color="bg-slate-400" /></div></MethodSection>
    <section className="px-5 pb-20 sm:px-8 lg:px-10"><div className="mx-auto max-w-4xl rounded-[2rem] border border-amber-900/15 bg-amber-50 p-7 sm:p-10"><h2 className="text-2xl font-bold text-amber-950">Batas penggunaan</h2><p className="mt-4 leading-7 text-amber-950/80">Jangan gunakan estimasi EcoSpend untuk audit karbon, laporan ESG atau regulasi, perbandingan ilmiah, keputusan investasi, kompensasi emisi, sertifikasi, klaim net-zero, atau klaim pemasaran lingkungan. Untuk kebutuhan tersebut, gunakan metodologi yang sesuai, data primer, dan profesional berkualifikasi.</p></div></section>
  </main><SiteFooter /></div>;
}

function MethodSection({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { return <section className="border-t border-emerald-950/10 px-5 py-16 sm:px-8 lg:px-10 lg:py-20"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[220px_1fr]"><div><p className="font-mono text-sm text-emerald-700">{number}</p><h2 className="mt-2 text-2xl font-bold tracking-tight text-emerald-950">{title}</h2></div><div className="max-w-4xl leading-7 text-slate-600">{children}</div></div></section>; }
function MethodCard({ icon: Icon, title, formula, text }: { icon: typeof Calculator; title: string; formula: string; text: string }) { return <article className="rounded-2xl border border-emerald-950/10 bg-white p-6"><Icon className="size-6 text-emerald-700" aria-hidden="true" /><h3 className="mt-4 text-lg font-bold text-emerald-950">{title}</h3><code className="mt-4 block rounded-xl bg-emerald-950 p-4 text-xs text-lime-300">{formula}</code><p className="mt-4 text-sm leading-6">{text}</p></article>; }
function Confidence({ label, text, color }: { label: string; text: string; color: string }) { return <div className="rounded-xl border border-emerald-950/10 bg-white p-4"><div className="flex items-center gap-2"><span className={`size-2.5 rounded-full ${color}`} /><strong className="text-sm text-slate-800">{label}</strong></div><p className="mt-2 text-xs leading-5">{text}</p></div>; }
