import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage } from "@/components/public/legal-page";

export const metadata: Metadata = { title: "Syarat Penggunaan | EcoSpend", description: "Ketentuan penggunaan dan batasan EcoSpend." };

const sections = [
  { id: "penerimaan", title: "Penerimaan ketentuan", content: <><p>Dengan menggunakan EcoSpend, Anda menyetujui ketentuan ini dan <Link href="/privacy">Kebijakan Privasi</Link>. Jika tidak setuju, jangan gunakan layanan.</p><p>Proyek ini masih dalam pengembangan. Ketersediaan fitur, bentuk data, dan perilaku dapat berubah. Deployment demo tidak menjanjikan penyimpanan atau ketersediaan berkelanjutan.</p></> },
  { id: "kelayakan", title: "Kelayakan dan akun", content: <><p>Anda harus memiliki kapasitas hukum untuk menyetujui ketentuan ini sesuai aturan yang berlaku. Anda bertanggung jawab atas informasi akun yang benar, kata sandi yang kuat, dan aktivitas melalui sesi Anda.</p><p>Segera keluar pada perangkat bersama. Jangan membagikan token, tautan pemulihan, atau kredensial. Laporkan dugaan akses tidak sah melalui support@ecospend.local (placeholder; akan diganti sebelum peluncuran publik).</p></> },
  { id: "penggunaan", title: "Penggunaan yang diperbolehkan", content: <><p>Gunakan EcoSpend untuk pencatatan dan eksplorasi keuangan pribadi secara sah. Anda tidak boleh:</p><ul><li>mengakses akun atau data orang lain tanpa izin;</li><li>mengganggu layanan, menghindari batas penggunaan, atau menguji kerentanan tanpa otorisasi;</li><li>mengunggah malware, data yang tidak berhak Anda proses, atau konten melanggar hukum;</li><li>menggunakan hasil demo sebagai bukti audit, sertifikasi, atau klaim resmi.</li></ul></> },
  { id: "data", title: "Data dan tanggung jawab Anda", content: <><p>Anda mempertahankan hak atas data yang Anda masukkan. Anda memberi layanan izin terbatas untuk memproses data tersebut hanya agar fungsi yang diminta dapat berjalan.</p><p>Pastikan Anda memiliki hak untuk memasukkan data. Simpan salinan penting Anda sendiri; EcoSpend bukan arsip, bank, sistem akuntansi, atau fasilitas penyimpanan yang dijamin.</p></> },
  { id: "finansial", title: "Bukan nasihat finansial", content: <><p>Ringkasan, anggaran, tren, dan informasi lain disediakan untuk pencatatan pribadi. Informasi tersebut bukan nasihat investasi, pajak, hukum, akuntansi, kredit, atau rekomendasi untuk membeli produk.</p><p>Periksa kembali angka penting dan konsultasikan dengan profesional berkualifikasi untuk keputusan yang membutuhkan pertimbangan khusus.</p></> },
  { id: "karbon", title: "Batas estimasi karbon", content: <><p>Angka CO₂e adalah estimasi berdasarkan aktivitas atau nilai belanja dan faktor yang mungkin disederhanakan, tidak lengkap, atau usang. Kualitas hasil bergantung pada kategori, satuan, wilayah, waktu, dan sumber faktor.</p><p>Hasil tidak boleh digunakan untuk audit, pelaporan ESG/regulasi, kompensasi emisi, klaim net-zero, perbandingan ilmiah, atau sertifikasi lingkungan.</p></> },
  { id: "ketersediaan", title: "Ketersediaan dan perubahan", content: <><p>Layanan dapat diubah, dibatasi, dihentikan sementara, atau dihentikan. Paket gratis penyedia dapat memiliki kuota, cold start, retensi, dan batas availability.</p><p>Shell PWA bukan jaminan fungsi offline penuh. Data privat dan mutasi memerlukan koneksi serta konfirmasi server kecuali dinyatakan lain.</p></> },
  { id: "jaminan", title: "Penafian dan batas tanggung jawab", content: <><p>Sejauh diperbolehkan hukum, EcoSpend disediakan “sebagaimana adanya” tanpa jaminan bahwa layanan selalu tersedia, bebas kesalahan, atau cocok untuk tujuan tertentu.</p><p>Operator tidak bertanggung jawab atas keputusan yang hanya mengandalkan estimasi, kehilangan akibat data input keliru, atau layanan pihak ketiga. Ketentuan ini tidak mengecualikan tanggung jawab yang tidak boleh dikecualikan menurut hukum.</p></> },
  { id: "penghentian", title: "Penghentian", content: <><p>Akses dapat dibatasi bila penggunaan mengancam keamanan, melanggar hukum, atau melanggar ketentuan ini. Anda dapat menghentikan penggunaan dan menghapus akun melalui Pengaturan; retensi backup mengikuti Kebijakan Privasi.</p><p>Bagian tentang kepemilikan data, penafian, batas tanggung jawab, dan ketentuan lain yang menurut sifatnya tetap berlaku akan bertahan setelah penghentian.</p></> },
  { id: "perubahan", title: "Perubahan ketentuan", content: <p>Ketentuan dapat diperbarui untuk mencerminkan perubahan fitur, risiko, atau kewajiban. Perubahan material sebaiknya diberitahukan sebelum berlaku. Penggunaan setelah tanggal berlaku berarti menerima versi baru.</p> },
] as const;

export default function TermsPage() { return <LegalPage eyebrow="Aturan yang jelas" title="Syarat Penggunaan" intro="Ketentuan ini menjelaskan cara menggunakan EcoSpend secara bertanggung jawab, serta batas penting untuk informasi finansial dan estimasi karbon." updated="8 September 2026" sections={sections} />; }
