"use client";

import { useState } from "react";
import { CalendarDays, Home, Leaf, Plus, ShieldCheck, Sparkles, Trophy } from "lucide-react";
import { toast } from "sonner";
import { useDemoStore } from "./demo-store";
import { createId, formatDate, formatRupiah } from "./format";
import type { Goal } from "./types";
import { Card, Modal, PageHeader, Progress, buttonPrimary, buttonSecondary, inputClass, labelClass } from "./ui";

const icons = { leaf: Leaf, home: Home, shield: ShieldCheck };
export function GoalManager() {
  const store = useDemoStore(); const [modal, setModal] = useState(false); const [contribution, setContribution] = useState<Goal | null>(null); const [amount, setAmount] = useState("100000");
  const [form, setForm] = useState<Omit<Goal, "id" | "saved">>({ name: "", target: 5000000, deadline: "2027-12-31", icon: "leaf" });
  const save = () => { if (form.name.trim().length < 2 || form.target <= 0) return toast.error("Lengkapi nama dan nominal target"); store.saveGoal({ ...form, id: createId("goal"), saved: 0 }); setModal(false); toast.success("Target dibuat"); };
  const contribute = () => { const value = Number(amount); if (!contribution || !Number.isFinite(value) || value <= 0) return; store.contributeGoal(contribution.id, value); setContribution(null); toast.success("Kontribusi ditambahkan"); };
  const totalTarget = store.goals.reduce((sum, item) => sum + item.target, 0); const totalSaved = store.goals.reduce((sum, item) => sum + item.saved, 0);
  return <div className="space-y-6"><PageHeader eyebrow="Masa depan" title="Target keuangan" description="Ubah rencana besar menjadi langkah kecil yang terukur dan konsisten." actions={<button type="button" onClick={() => setModal(true)} className={buttonPrimary}><Plus className="size-4" />Buat target</button>} />
    <Card className="overflow-hidden bg-gradient-to-br from-emerald-800 to-emerald-600 p-6 text-white"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><span className="grid size-14 place-items-center rounded-2xl bg-white/15"><Trophy className="size-7" /></span><div className="flex-1"><p className="text-sm text-emerald-100">Kemajuan seluruh target</p><p className="mt-1 text-2xl font-bold">{formatRupiah(totalSaved)} <span className="text-sm font-normal text-emerald-100">dari {formatRupiah(totalTarget)}</span></p><div className="mt-3 h-2.5 rounded-full bg-white/20"><div className="h-full rounded-full bg-white" style={{ width: `${totalSaved / totalTarget * 100}%` }} /></div></div></div></Card>
    <div className="grid gap-5 lg:grid-cols-3">{store.goals.map((item) => { const Icon = icons[item.icon]; const progress = item.saved / item.target * 100; const remaining = item.target - item.saved; const months = Math.max(1, Math.ceil((new Date(item.deadline).getTime() - new Date("2026-09-08").getTime()) / 2.628e9)); return <Card key={item.id} className="p-5"><div className="flex items-start justify-between"><span className="grid size-11 place-items-center rounded-xl bg-[#1e6f4e]/[.08] text-[#1e6f4e] dark:bg-emerald-950"><Icon className="size-5" /></span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold dark:bg-slate-800">{Math.round(progress)}%</span></div><h2 className="mt-4 text-lg font-bold">{item.name}</h2><p className="mt-1 flex items-center gap-1.5 text-xs text-slate-600"><CalendarDays className="size-3.5" />Tenggat {formatDate(item.deadline)}</p><div className="mt-5"><Progress value={progress} label={`Kemajuan ${item.name}`} /><div className="mt-2 flex justify-between text-sm"><strong>{formatRupiah(item.saved)}</strong><span className="text-slate-600">{formatRupiah(item.target)}</span></div></div><div className="mt-4 rounded-xl bg-slate-50 p-3 text-xs text-slate-600 dark:bg-slate-800 dark:text-slate-300">Saran kontribusi <strong>{formatRupiah(Math.ceil(remaining / months / 10000) * 10000)}</strong> per bulan</div><button type="button" onClick={() => { setContribution(item); setAmount("100000"); }} disabled={progress >= 100} className={`${buttonSecondary} mt-4 w-full`}><Plus className="size-4" />{progress >= 100 ? "Target tercapai" : "Tambah kontribusi"}</button></Card>; })}</div>
    <Card className="flex gap-3 p-5"><Sparkles className="mt-0.5 size-5 shrink-0 text-amber-600" /><div><h2 className="font-semibold">Tips konsisten</h2><p className="mt-1 text-sm text-slate-600">Aktifkan transaksi berulang di Pengaturan agar kontribusi target menjadi bagian tetap dari anggaran bulanan.</p></div></Card>
    <Modal open={modal} title="Buat target baru" onClose={() => setModal(false)}><div className="space-y-4"><label><span className={labelClass}>Nama target</span><input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className={inputClass} placeholder="Contoh: Sepeda listrik" /></label><label><span className={labelClass}>Nominal target</span><input type="number" min="1" value={form.target} onChange={(e) => setForm({ ...form, target: Number(e.target.value) })} className={inputClass} /></label><label><span className={labelClass}>Tenggat</span><input type="date" value={form.deadline} onChange={(e) => setForm({ ...form, deadline: e.target.value })} className={inputClass} /></label><label><span className={labelClass}>Ikon</span><select value={form.icon} onChange={(e) => setForm({ ...form, icon: e.target.value as Goal["icon"] })} className={inputClass}><option value="leaf">Lingkungan</option><option value="home">Rumah</option><option value="shield">Keamanan</option></select></label><div className="flex justify-end gap-2"><button type="button" onClick={() => setModal(false)} className={buttonSecondary}>Batal</button><button type="button" onClick={save} className={buttonPrimary}>Buat target</button></div></div></Modal>
    <Modal open={Boolean(contribution)} title={`Kontribusi ke ${contribution?.name ?? "target"}`} onClose={() => setContribution(null)}><div className="space-y-4"><label><span className={labelClass}>Nominal kontribusi</span><input type="number" min="1" step="10000" value={amount} onChange={(e) => setAmount(e.target.value)} className={inputClass} /></label><p className="text-sm text-slate-600">Kontribusi memperbarui kemajuan target demo, tanpa memindahkan saldo akun.</p><div className="flex justify-end gap-2"><button type="button" onClick={() => setContribution(null)} className={buttonSecondary}>Batal</button><button type="button" onClick={contribute} className={buttonPrimary}>Tambah kontribusi</button></div></div></Modal>
  </div>;
}
