"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useTheme } from "next-themes";
import { useState } from "react";
import { Bell, Crown, Download, LogOut, Moon, Palette, Plus, Repeat2, Save, Shield, Trash2, UserRound, WalletCards } from "lucide-react";
import { toast } from "sonner";
import { clearEcoSpendWorkerCaches } from "@/components/public/pwa-register";
import { createOptionalBrowserClient } from "@/lib/supabase/client";
import { AccountDeletion } from "./account-deletion";
import { categories } from "./demo-data";
import { useDemoStore } from "./demo-store";
import { createId, downloadBlob, formatRupiah } from "./format";
import type { Account, Recurring } from "./types";
import { Card, Modal, PageHeader, Toggle, buttonPrimary, buttonSecondary, inputClass, labelClass } from "./ui";

const ECOSPEND_STORAGE_PREFIX = "ecospend-";
const exportFormulaPrefix = /^[\s\t]*[=+\-@]/;
export const sanitizeExportValue = (value: unknown) => typeof value === "string" && exportFormulaPrefix.test(value) ? `'${value}` : value;
const sanitizeExport = (value: unknown): unknown => {
  if (Array.isArray(value)) return value.map(sanitizeExport);
  if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, sanitizeExport(item)]));
  return sanitizeExportValue(value);
};

function clearEcoSpendStorage() {
  for (const storage of [window.localStorage, window.sessionStorage]) {
    for (let index = storage.length - 1; index >= 0; index -= 1) {
      const key = storage.key(index);
      if (key?.startsWith(ECOSPEND_STORAGE_PREFIX)) storage.removeItem(key);
    }
  }
}

export function SettingsDashboard() {
  const router = useRouter();
  const { setTheme } = useTheme();
  const store = useDemoStore(); const [accountModal,setAccountModal]=useState(false); const [recurringModal,setRecurringModal]=useState(false); const [ruleMerchant,setRuleMerchant]=useState(""); const [ruleCategory,setRuleCategory]=useState(categories[0]);
  const [account,setAccount]=useState<Omit<Account,"id">>({name:"",type:"Bank",balance:0,color:"#167a5b"}); const [recurring,setRecurring]=useState<Omit<Recurring,"id"|"active">>({name:"",category:categories[0],amount:0,day:1});
  const [deleteOpen,setDeleteOpen]=useState(false); const [typed,setTyped]=useState("");
  const [loggingOut,setLoggingOut]=useState(false); const [notificationPermission,setNotificationPermission]=useState<NotificationPermission | "unsupported">(() => typeof Notification === "undefined" ? "unsupported" : Notification.permission);
  const p=store.preferences;
  const saveProfile=async()=>{const name=p.displayName.trim();if(name.length<2)return toast.error("Nama tampilan minimal 2 karakter");const response=await fetch("/api/profile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({displayName:name})}).catch(()=>null);if(response?.ok){toast.success("Profil disimpan");return;}toast.error(response ? "Profil belum dapat disimpan" : "Layanan profil belum tersedia; perubahan hanya tersimpan di perangkat ini");};
  const requestNotifications=async()=>{if(typeof Notification==="undefined"){setNotificationPermission("unsupported");window.dispatchEvent(new CustomEvent("ecospend:in-app-notification"));return toast.error("Notifikasi browser tidak didukung; notifikasi dalam aplikasi tetap aktif");}const permission=await Notification.requestPermission();setNotificationPermission(permission);if(permission==="granted"){new Notification("Notifikasi EcoSpend aktif",{body:"Peringatan yang Anda pilih dapat ditampilkan oleh browser.",icon:"/icons/icon.svg"});toast.success("Notifikasi browser diaktifkan");}else{window.dispatchEvent(new CustomEvent("ecospend:in-app-notification"));toast.error("Izin browser tidak diberikan; notifikasi akan tampil di dalam aplikasi");}};
  const saveAccount=()=>{if(account.name.length<2||account.balance<0)return toast.error("Lengkapi data akun");store.saveAccount({...account,id:createId("account")});setAccountModal(false);toast.success("Akun ditambahkan");};
  const removeOrArchiveAccount=async(item:Account)=>{const transactionCount=store.transactions.filter(transaction=>transaction.account===item.name||transaction.destinationAccount===item.name).length;if(transactionCount>0){const response=await fetch("/api/accounts",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id,archived:true})}).catch(()=>null);if(response?.ok)toast.success("Akun diarsipkan; riwayat transaksi tetap tersimpan");else toast.error("Layanan arsip akun belum tersedia; akun dan transaksi tidak dihapus");return;}store.deleteAccount(item.id);toast.success("Akun kosong dihapus");};
  const saveRecurring=()=>{if(recurring.name.length<2||recurring.amount<=0)return toast.error("Lengkapi transaksi berulang");store.saveRecurring({...recurring,id:createId("recurring"),active:true});setRecurringModal(false);toast.success("Transaksi berulang dibuat");};
  const exportAll=async()=>{const response=await fetch("/api/export",{headers:{Accept:"application/json"}}).catch(()=>null);if(response?.ok){downloadBlob(await response.blob(),"ecospend-data.json","application/json");toast.success("Data akun diunduh");return;}downloadBlob(JSON.stringify(sanitizeExport({exportedAt:new Date().toISOString(),data:{transactions:store.transactions,budgets:store.budgets,goals:store.goals,accounts:store.accounts,recurring:store.recurring,preferences:store.preferences,rules:store.rules}}),null,2),"ecospend-data-demo.json","application/json");toast.success("Layanan ekspor tidak tersedia; data demo yang aman diunduh");};
  const logout=async()=>{if(loggingOut)return;setLoggingOut(true);try{const result=createOptionalBrowserClient();if(result.configured){const {error}=await result.client.auth.signOut({scope:"local"});if(error)throw error;}clearEcoSpendStorage();await clearEcoSpendWorkerCaches(true);toast.success("Anda telah keluar");router.replace("/login");router.refresh();}catch{toast.error("Gagal keluar. Periksa koneksi lalu coba lagi.");setLoggingOut(false);}};
  return <div className="space-y-6"><PageHeader eyebrow="Kendali akun" title="Pengaturan" description="Atur pengalaman EcoSpend, aturan otomatis, akun, dan data demo Anda." />
    <Card className="overflow-hidden border-emerald-700/20 bg-gradient-to-br from-[#082419] to-[#0e3b2c] p-5 text-white shadow-xl shadow-emerald-950/20"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-2xl bg-lime-300 text-[#082419]"><Crown className="size-5" /></span><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-display text-lg font-extrabold">Paket Pemula</h2><span className="rounded-full bg-white/10 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-emerald-100">Gratis Selamanya</span></div><p className="mt-1 max-w-xl text-sm leading-6 text-emerald-100/75">Nikmati 50 transaksi dan 1 akun setiap bulan. Tingkatkan ke Pro untuk akun, transaksi, impor bank, dan lampiran struk tanpa batas.</p></div></div><Link href="/pricing" className="inline-flex min-h-11 shrink-0 items-center justify-center rounded-xl bg-lime-300 px-5 text-sm font-bold text-[#082419] shadow transition hover:bg-lime-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white">Lihat Paket Pro</Link></div></Card>
    <div className="grid gap-6 xl:grid-cols-[1fr_1.4fr]"><div className="space-y-6"><Card className="p-5"><div className="flex items-center gap-2"><UserRound className="size-5 text-emerald-700"/><h2 className="font-bold">Profil</h2></div><div className="mt-4 space-y-4"><label><span className={labelClass}>Nama tampilan</span><input value={p.displayName} onChange={e=>store.setPreferences({...p,displayName:e.target.value})} className={inputClass}/></label><label><span className={labelClass}>Mata uang</span><select disabled className={inputClass}><option>IDR — Rupiah Indonesia</option></select></label><button type="button" onClick={saveProfile} className={buttonPrimary}><Save className="size-4"/>Simpan profil</button></div></Card>
    <Card className="p-5"><div className="flex items-center gap-2"><Palette className="size-5 text-violet-700"/><h2 className="font-bold">Tampilan</h2></div><label className="mt-4 block"><span className={labelClass}>Tema</span><select value={p.theme} onChange={e=>{const theme=e.target.value as typeof p.theme;store.setPreferences({...p,theme});setTheme(theme);}} className={inputClass}><option value="system">Ikuti sistem</option><option value="light">Terang</option><option value="dark">Gelap</option></select></label></Card>
    <Card className="p-5"><div className="flex items-center gap-2"><Bell className="size-5 text-blue-700"/><h2 className="font-bold">Notifikasi</h2></div><div className="mt-3 divide-y divide-slate-100 dark:divide-slate-800"><Toggle label="Peringatan anggaran" description="Saat penggunaan mendekati batas" checked={p.notifications.budget} onChange={budget=>store.setPreferences({...p,notifications:{...p.notifications,budget}})}/><Toggle label="Kemajuan target" description="Ringkasan pencapaian target" checked={p.notifications.goals} onChange={goals=>store.setPreferences({...p,notifications:{...p.notifications,goals}})}/><Toggle label="Ringkasan mingguan" description="Ikhtisar setiap akhir pekan" checked={p.notifications.weekly} onChange={weekly=>store.setPreferences({...p,notifications:{...p.notifications,weekly}})}/></div><div className="mt-4 rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><p className="text-xs text-slate-600 dark:text-slate-300">Izin browser: {notificationPermission === "granted" ? "diizinkan" : notificationPermission === "denied" ? "ditolak" : notificationPermission === "unsupported" ? "tidak didukung" : "belum diminta"}. Tanpa izin, peringatan tetap tampil di panel aplikasi.</p><button type="button" onClick={requestNotifications} disabled={notificationPermission === "granted"} className={`${buttonSecondary} mt-3`}>{notificationPermission === "granted" ? "Notifikasi browser aktif" : "Aktifkan notifikasi browser"}</button></div></Card></div>
    <div className="space-y-6"><Card className="p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><WalletCards className="size-5 text-emerald-700"/><div><h2 className="font-bold">Akun keuangan</h2><p className="text-xs text-slate-600">Saldo demo tanpa nomor rekening</p></div></div><button type="button" onClick={()=>setAccountModal(true)} className={buttonSecondary}><Plus className="size-4"/>Tambah</button></div><div className="mt-4 divide-y divide-slate-100 dark:divide-slate-800">{store.accounts.map(i=>{const transactionCount=store.transactions.filter(transaction=>transaction.account===i.name||transaction.destinationAccount===i.name).length;return <div key={i.id} className="flex items-center gap-3 py-3"><span className="size-3 rounded-full" style={{background:i.color}}/><div className="flex-1"><p className="text-sm font-semibold">{i.name}</p><p className="text-xs text-slate-600">{i.type}{transactionCount>0?` · ${transactionCount} transaksi tersimpan`:""}</p></div><strong className="text-sm">{formatRupiah(i.balance)}</strong><button type="button" onClick={()=>void removeOrArchiveAccount(i)} disabled={store.accounts.length<=1} aria-label={transactionCount>0?`Arsipkan ${i.name}`:`Hapus ${i.name}`} className="grid size-11 shrink-0 place-items-center rounded-xl text-rose-600 disabled:opacity-30"><Trash2 className="size-4"/></button></div>;})}</div></Card>
    <Card id="berulang" className="p-5 scroll-mt-24"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Repeat2 className="size-5 text-blue-700"/><div><h2 className="font-bold">Transaksi berulang</h2><p className="text-xs text-slate-600">Jadwal pengingat bulanan</p></div></div><button type="button" onClick={()=>setRecurringModal(true)} className={buttonSecondary}><Plus className="size-4"/>Tambah</button></div><div className="mt-4 divide-y divide-slate-100 dark:divide-slate-800">{store.recurring.map(i=><div key={i.id} className="flex items-center gap-3 py-3"><div className="flex-1"><p className="text-sm font-semibold">{i.name}</p><p className="text-xs text-slate-600">Tanggal {i.day} · {i.category} · {formatRupiah(i.amount)}</p></div><Toggle label={i.active?"Aktif":"Nonaktif"} checked={i.active} onChange={active=>store.saveRecurring({...i,active})}/><button type="button" onClick={()=>store.deleteRecurring(i.id)} aria-label={`Hapus ${i.name}`} className="grid size-11 shrink-0 place-items-center rounded-xl text-rose-600"><Trash2 className="size-4"/></button></div>)}</div></Card>
    <Card className="p-5"><div className="flex items-center gap-2"><Moon className="size-5 text-teal-700"/><h2 className="font-bold">Perhitungan karbon</h2></div><label className="mt-4 block"><span className={labelClass}>Metode faktor emisi</span><select value={p.carbonMethod} onChange={e=>store.setPreferences({...p,carbonMethod:e.target.value as typeof p.carbonMethod})} className={inputClass}><option value="rata-rata">Rata-rata sektor</option><option value="konservatif">Konservatif (batas atas)</option></select></label></Card>
    <Card className="p-5"><div className="flex items-center gap-2"><Shield className="size-5 text-amber-700"/><h2 className="font-bold">Aturan merchant & kategori</h2></div><div className="mt-4 flex flex-col gap-2 sm:flex-row"><input value={ruleMerchant} onChange={e=>setRuleMerchant(e.target.value)} placeholder="Kata kunci merchant" className={inputClass}/><select value={ruleCategory} onChange={e=>setRuleCategory(e.target.value)} className={inputClass}>{categories.map(c=><option key={c}>{c}</option>)}</select><button type="button" onClick={()=>{if(ruleMerchant.trim().length<2)return toast.error("Isi kata kunci merchant");store.setRules([...store.rules,{id:createId("rule"),merchant:ruleMerchant.trim(),category:ruleCategory}]);setRuleMerchant("");toast.success("Aturan ditambahkan");}} className={buttonPrimary}>Tambah</button></div><div className="mt-3 space-y-2">{store.rules.map(r=><div key={r.id} className="flex items-center rounded-xl bg-slate-50 px-3 py-2 text-sm dark:bg-slate-800"><strong>{r.merchant}</strong><span className="mx-2 text-slate-500">→</span><span>{r.category}</span><button type="button" aria-label={`Hapus aturan ${r.merchant}`} onClick={()=>store.setRules(store.rules.filter(i=>i.id!==r.id))} className="ml-auto text-rose-600"><Trash2 className="size-4"/></button></div>)}</div></Card></div></div>
    <Card className="p-5"><h2 className="font-bold">Data & sesi</h2><p className="mt-1 text-sm text-slate-600">Ekspor salinan, mulai ulang demo, atau keluar. Tidak ada data pribadi dalam dataset demo.</p><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={()=>void exportAll()} className={buttonSecondary}><Download className="size-4"/>Ekspor semua data</button><button type="button" onClick={logout} disabled={loggingOut} className={buttonSecondary}><LogOut className="size-4"/>{loggingOut?"Sedang keluar…":"Keluar"}</button><button type="button" onClick={()=>setDeleteOpen(true)} className={`${buttonSecondary} text-rose-700`}><Trash2 className="size-4"/>Hapus data demo</button><AccountDeletion /></div></Card>
    <Modal open={accountModal} title="Tambah akun" onClose={()=>setAccountModal(false)}><div className="space-y-4"><label><span className={labelClass}>Nama akun</span><input value={account.name} onChange={e=>setAccount({...account,name:e.target.value})} className={inputClass}/></label><label><span className={labelClass}>Jenis</span><select value={account.type} onChange={e=>setAccount({...account,type:e.target.value as Account["type"]})} className={inputClass}><option>Bank</option><option>Dompet digital</option><option>Tunai</option></select></label><label><span className={labelClass}>Saldo awal</span><input type="number" min="0" value={account.balance} onChange={e=>setAccount({...account,balance:Number(e.target.value)})} className={inputClass}/></label><label><span className={labelClass}>Warna</span><input type="color" value={account.color} onChange={e=>setAccount({...account,color:e.target.value})} className="h-11 w-full rounded-xl border p-1"/></label><div className="flex justify-end gap-2"><button type="button" onClick={()=>setAccountModal(false)} className={buttonSecondary}>Batal</button><button type="button" onClick={saveAccount} className={buttonPrimary}>Simpan</button></div></div></Modal>
    <Modal open={recurringModal} title="Tambah transaksi berulang" onClose={()=>setRecurringModal(false)}><div className="space-y-4"><label><span className={labelClass}>Nama</span><input value={recurring.name} onChange={e=>setRecurring({...recurring,name:e.target.value})} className={inputClass}/></label><label><span className={labelClass}>Kategori</span><select value={recurring.category} onChange={e=>setRecurring({...recurring,category:e.target.value})} className={inputClass}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label><span className={labelClass}>Nominal</span><input type="number" min="1" value={recurring.amount} onChange={e=>setRecurring({...recurring,amount:Number(e.target.value)})} className={inputClass}/></label><label><span className={labelClass}>Tanggal setiap bulan</span><input type="number" min="1" max="28" value={recurring.day} onChange={e=>setRecurring({...recurring,day:Number(e.target.value)})} className={inputClass}/></label><div className="flex justify-end gap-2"><button type="button" onClick={()=>setRecurringModal(false)} className={buttonSecondary}>Batal</button><button type="button" onClick={saveRecurring} className={buttonPrimary}>Simpan</button></div></div></Modal>
    <Modal open={deleteOpen} title="Hapus seluruh data demo" description="Ketik HAPUS untuk mengonfirmasi. Tindakan ini membersihkan penyimpanan EcoSpend lalu memuat ulang dataset demo awal." onClose={()=>{setDeleteOpen(false);setTyped("");}}><div className="space-y-4"><input value={typed} onChange={e=>setTyped(e.target.value)} placeholder="Ketik HAPUS" className={inputClass}/><div className="flex justify-end gap-2"><button type="button" onClick={()=>setDeleteOpen(false)} className={buttonSecondary}>Batal</button><button type="button" disabled={typed!=="HAPUS"} onClick={()=>{clearEcoSpendStorage();store.resetData();setDeleteOpen(false);setTyped("");toast.success("Data EcoSpend dibersihkan dan demo awal dimuat ulang");}} className={`${buttonPrimary} bg-rose-700 hover:bg-rose-800`}>Hapus data</button></div></div></Modal>
  </div>;
}
