import type { Metadata } from "next";
import { LegalPage } from "@/components/public/legal-page";

export const metadata: Metadata = { title: "Kebijakan Privasi | EcoSpend", description: "Cara EcoSpend merancang pengumpulan, penggunaan, perlindungan, dan penghapusan data." };

const sections = [
  { id: "ringkasan", title: "Ringkasan", content: <><p>EcoSpend membantu pencatatan keuangan pribadi dan estimasi dampak karbon. Prinsip kami adalah <strong>mengumpulkan sesedikit mungkin data</strong>, menjelaskan tujuannya, dan membatasi akses berdasarkan kebutuhan.</p><p>Kontak privasi: support@ecospend.local (placeholder; akan diganti sebelum peluncuran publik). Versi proyek ini masih dalam pengembangan.</p></> },
  { id: "data", title: "Data yang dapat diproses", content: <><p>Jika backend nyata diaktifkan, data dapat mencakup:</p><ul><li>identitas akun seperti email dan pengenal pengguna;</li><li>transaksi, akun finansial, kategori, anggaran, dan tujuan yang Anda masukkan;</li><li>aktivitas untuk estimasi karbon, preferensi, serta metadata teknis minimum;</li><li>file impor atau lampiran hanya ketika fitur tersebut digunakan.</li></ul><p>Mode demo menggunakan data sintetis dan tidak boleh dianggap sebagai penyimpanan persisten.</p></> },
  { id: "tujuan", title: "Tujuan penggunaan", content: <><p>Data digunakan untuk menyediakan fungsi yang Anda minta: autentikasi, pencatatan, ringkasan, anggaran, estimasi CO₂e, pemulihan akun, ekspor/penghapusan, keamanan, dan perbaikan kesalahan.</p><p>EcoSpend tidak dirancang untuk menjual data transaksi atau menjadikannya profil iklan. Integrasi analytics atau pemantauan kesalahan tidak boleh menerima isi transaksi atau identitas tanpa kebutuhan, dasar pemrosesan, dan redaksi yang jelas.</p></> },
  { id: "karbon", title: "Estimasi karbon", content: <><p>Estimasi dapat memakai data aktivitas atau nilai belanja, kategori, wilayah, periode, serta faktor emisi. Faktor sebaiknya menyimpan sumber, versi, satuan, dan masa berlaku agar hasil dapat ditelusuri.</p><p><strong>Hasil bersifat indikatif.</strong> Hasil bukan pengukuran langsung, audit, sertifikasi, nasihat finansial, atau dasar klaim lingkungan dan pelaporan regulasi.</p></> },
  { id: "penyimpanan", title: "Penyimpanan dan keamanan", content: <><p>Pada deployment nyata, data akun direncanakan disimpan melalui Supabase dengan Row Level Security (RLS). Konfigurasi publik browser bukan kunci administratif; keamanan tetap bergantung pada kebijakan database yang telah diuji.</p><p>Token, cookie sesi, kata sandi, kunci administratif, dan payload sensitif tidak boleh ditulis ke log. HTTPS, pembatasan akses, backup, retensi, serta respons insiden wajib diverifikasi oleh operator sebelum rilis.</p></> },
  { id: "pihak-ketiga", title: "Penyedia layanan", content: <><p>Deployment dapat menggunakan penyedia hosting dan Supabase untuk autentikasi/database. Daftar subprosesor, lokasi pemrosesan, dan ketentuan aktual harus dipublikasikan oleh operator deployment sebelum menerima data nyata.</p><p>Kebijakan penyedia dapat berlaku terpisah. EcoSpend tidak mengirim data ke layanan eksternal hanya karena mode demo dibuka.</p></> },
  { id: "hak", title: "Pilihan dan hak Anda", content: <><p>Sebelum penggunaan publik, deployment harus menyediakan cara yang wajar untuk mengakses, memperbaiki, mengekspor, dan menghapus akun serta data terkait. Anda juga dapat berhenti menggunakan layanan dan menghapus data browser demo.</p><p>Permintaan hak harus diverifikasi agar data tidak diserahkan atau dihapus atas permintaan pihak yang tidak berwenang.</p></> },
  { id: "retensi", title: "Retensi dan penghapusan", content: <><p>Data aktif disimpan selama akun masih ada. Cadangan database dibuat otomatis setiap hari oleh penyedia dan berputar maksimal 7 hari. Ketika akun dihapus, data aktif dihapus seketika; salinan pada backup lama hilang sendiri saat backup tersebut tertimpa, maksimal 7 hari setelah penghapusan.</p><p>Ketika akun dihapus, data aktif terkait harus dijadwalkan untuk dihapus, dengan penjelasan transparan apabila backup memerlukan waktu tambahan untuk berputar.</p></> },
  { id: "perubahan", title: "Perubahan kebijakan", content: <p>Kebijakan dapat diperbarui seiring fitur dan deployment berkembang. Tanggal pembaruan akan diubah, dan perubahan material sebaiknya diberitahukan melalui produk atau kanal yang sesuai.</p> },
] as const;

export default function PrivacyPage() { return <LegalPage eyebrow="Privasi sebagai dasar" title="Kebijakan Privasi" intro="Penjelasan yang lugas tentang data apa yang dapat diproses EcoSpend, untuk apa, dan batas perlindungan yang harus dipenuhi sebelum penggunaan nyata." updated="8 September 2026" sections={sections} />; }
